name: Deploy to AWS EC2 UTS-Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to ECS
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
        sudo docker pull fahdira/frontend-uas

        # Stop and remove the container only if it exists
        if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^frontend\$"; then
          sudo docker stop frontend
          sudo docker rm frontend
        fi

        sudo docker run -d --name frontend -p 8080:80 fahdira/frontend-uas
        EOF
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}