# name: Deploy to EC2 Frontend

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Connect to EC2 and deploy
#         uses: appleboy/ssh-action@v0.1.10
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ec2-user
#           key: ${{ secrets.EC2_KEY }}
#           script: |
#             docker pull yourusername/frontend-app
#             docker stop frontend || true && docker rm frontend || true
#             docker run -d --name frontend -p 80:80 yourusername/frontend-app

name: Deploy to AWS EC2 UTS-Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to ECS
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.179.139.195 << 'EOF'
          docker pull fahdira/frontend-uas
          docker stop frontend || true && docker rm frontend || true
          docker run -d --name frontend -p 80:80 fahdira/frontend-uas
        EOF
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}